spring:
  application:
    name: gateway-service
  cloud:
    gateway:
      routes:
      - id: store
        uri: lb://STORE
        predicates:
        - Path=/store/**
        filters:
        - AuthFilter
        - name: CircuitBreaker
          args:
            name: store-service
            fallbackuri: /fallback
      - id: auth
        uri: lb://AUTH
        predicates:
          - Path=/auth/**
        filters:
          - name: CircuitBreaker
            args:
              name: auth-service
              fallbackuri: /fallback


server:
  port: 9195

management:
  endpoints:
    web:
      exposure:
        include: hystrix.stream

hystrix:
  command:
    fallbackcmd:
      execution:
        isolation:
          thread:
            timeoutInMilliseconds: 5000